//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodSubCategory
    {
        public int Id { get; set; }
        public Nullable<int> FoodMainCategoryId { get; set; }
        public string NameArabic { get; set; }
        public string NameEnglish { get; set; }
    
        public virtual FoodMainCategory FoodMainCategory { get; set; }
    }
}
