//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealtyLineContext : DbContext
    {
        public HealtyLineContext()
            : base("name=HealtyLineContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<FoodMainCategory> FoodMainCategories { get; set; }
        public virtual DbSet<FoodSubCategory> FoodSubCategories { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<RecipesIngredient> RecipesIngredients { get; set; }
        public virtual DbSet<RecipesStep> RecipesSteps { get; set; }
        public virtual DbSet<UserDeseas> UserDeseases { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
