//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthyLineProject.LocalResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bunless grass-fed burger topped with cheese, mushrooms and avocado atop a bed of greens.
        /// </summary>
        public static string Abunlessgrass2 {
            get {
                return ResourceManager.GetString("Abunlessgrass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add broccoli, potatoes and chicken broth, leave the mixture until it boils, then reduce heat and leave for 15 minutes until the ingredients are tender..
        /// </summary>
        public static string Addbroccoli4 {
            get {
                return ResourceManager.GetString("Addbroccoli4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addchicken and my heart for two minutes, pour it and garnish with sesame and coriander and serve hot alongside rice.
        /// </summary>
        public static string Addchicken6 {
            get {
                return ResourceManager.GetString("Addchicken6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add garlic and asparagus and stir for 3 minutes, then add salt, basil, black pepper and broth and leave the mixture until boiling for 10 minutes..
        /// </summary>
        public static string Addgarlic1 {
            get {
                return ResourceManager.GetString("Addgarlic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addsalt, cumin, lemon juice, olive oil and mix well..
        /// </summary>
        public static string Addsalt3 {
            get {
                return ResourceManager.GetString("Addsalt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the cream, filtered pasta, and stir until the ingredients mix, and simmer for 5 minutes..
        /// </summary>
        public static string Addthe1 {
            get {
                return ResourceManager.GetString("Addthe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to the same skillet onions, red pepper, yellow pepper, cumin, ground chili pepper, and stir over medium to high heat for 5 minutes.
        /// </summary>
        public static string Addtothe2 {
            get {
                return ResourceManager.GetString("Addtothe2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arugula salad with hard-boiled eggs, turkey, avocado and blue cheese..
        /// </summary>
        public static string Arugulasalad2 {
            get {
                return ResourceManager.GetString("Arugulasalad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asparagus: 2 cups (fresh or sorted / boiled and drained).
        /// </summary>
        public static string Asparagus1 {
            get {
                return ResourceManager.GetString("Asparagus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asparagus pasta for diet.
        /// </summary>
        public static string Asparaguspasta {
            get {
                return ResourceManager.GetString("Asparaguspasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Atkins diet focuses specifically on controlling insulin levels through a low-carb (or sugary) diet. This is because the consumption of large amounts of refined carbohydrates leads to high insulin levels and then drops rapidly, and this incites the body to store energy from the food that was consumed, which excludes the possibility that the body will use the stored fat as a source of energy. Therefore, those who follow this diet can eat whatever they want of protein and fats, but they should avoid carboh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Atkins {
            get {
                return ResourceManager.GetString("Atkins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atkins diet.
        /// </summary>
        public static string Atkinsdiet {
            get {
                return ResourceManager.GetString("Atkinsdiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avocado: 1 piece (peeled and sliced).
        /// </summary>
        public static string Avocadopiece2 {
            get {
                return ResourceManager.GetString("Avocadopiece2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avocados: Whole avocados can be added to almost any meal or snack..
        /// </summary>
        public static string Avocados2 {
            get {
                return ResourceManager.GetString("Avocados2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Bacon and eggs..
        /// </summary>
        public static string Bacon1 {
            get {
                return ResourceManager.GetString("Bacon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beans and legumes: Black beans, chickpeas, lentils and kidney beans..
        /// </summary>
        public static string Beans2 {
            get {
                return ResourceManager.GetString("Beans2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beef fajita for diet with fewer calories.
        /// </summary>
        public static string Beeffajita {
            get {
                return ResourceManager.GetString("Beeffajita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bell pepper stuffed with cheese and eggs.
        /// </summary>
        public static string Bellpepper2 {
            get {
                return ResourceManager.GetString("Bellpepper2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bison steak with cheesy broccoli.
        /// </summary>
        public static string Bisonsteak {
            get {
                return ResourceManager.GetString("Bisonsteak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Pepper: 1/4 teaspoon.
        /// </summary>
        public static string BlackPepper1 {
            get {
                return ResourceManager.GetString("BlackPepper1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beans and legumes: Black beans, chickpeas, lentils and kidney beans..
        /// </summary>
        public static string Boil1 {
            get {
                return ResourceManager.GetString("Boil1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boilcarrots, peas and celery in boiling water for 10 minutes, then filter and wash with cold water and put them in a dish..
        /// </summary>
        public static string Boilcarrots3 {
            get {
                return ResourceManager.GetString("Boilcarrots3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxing Exercise.
        /// </summary>
        public static string BoxingExercise {
            get {
                return ResourceManager.GetString("BoxingExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxing Exercises.
        /// </summary>
        public static string BoxingExercises {
            get {
                return ResourceManager.GetString("BoxingExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bread and baked goods: White bread, whole-wheat bread, crackers, cookies, doughnuts and rolls..
        /// </summary>
        public static string Bread2 {
            get {
                return ResourceManager.GetString("Bread2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broccoli Light Soup for Diet.
        /// </summary>
        public static string Broccoli {
            get {
                return ResourceManager.GetString("Broccoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broccoli: 3 cups (small or fresh cut flowers).
        /// </summary>
        public static string Broccoli4 {
            get {
                return ResourceManager.GetString("Broccoli4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgur: 3 cups (soft, half an hour in water).
        /// </summary>
        public static string Bulgur7 {
            get {
                return ResourceManager.GetString("Bulgur7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgur is scrubbed with two hands, and squeezed, until filtered from water, then added to the onion mixture. The components are hit in the machine..
        /// </summary>
        public static string Bulguris7 {
            get {
                return ResourceManager.GetString("Bulguris7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgur tomato salad for diet.
        /// </summary>
        public static string Bulgurtomato {
            get {
                return ResourceManager.GetString("Bulgurtomato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Bunless cheeseburger, with vegetables and butter..
        /// </summary>
        public static string Bunless1 {
            get {
                return ResourceManager.GetString("Bunless1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttock and Legand Hands Exercises.
        /// </summary>
        public static string ButtockandLegandHandsExercises {
            get {
                return ResourceManager.GetString("ButtockandLegandHandsExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttocks and Upper Legs Pain Exercises.
        /// </summary>
        public static string ButtocksandUpperLegsPainExercises {
            get {
                return ResourceManager.GetString("ButtocksandUpperLegsPainExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certain alcoholic beverages: Beer and sugary mixed drinks.
        /// </summary>
        public static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Ideal Weight.
        /// </summary>
        public static string CalculateIdealWeight {
            get {
                return ResourceManager.GetString("CalculateIdealWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calorie Guide.
        /// </summary>
        public static string CalorieGuide {
            get {
                return ResourceManager.GetString("CalorieGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardio and Legs Exercises.
        /// </summary>
        public static string CardioandLegsExercises {
            get {
                return ResourceManager.GetString("CardioandLegsExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiled carrot salad for a perfect diet.
        /// </summary>
        public static string carrot {
            get {
                return ResourceManager.GetString("carrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrots: 2 tablets (peeled and chopped slices).
        /// </summary>
        public static string Carrots3 {
            get {
                return ResourceManager.GetString("Carrots3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celery: half a cup (minced).
        /// </summary>
        public static string Celery3 {
            get {
                return ResourceManager.GetString("Celery3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certain alcoholic beverages: Beer and sugary mixed drinks.
        /// </summary>
        public static string Certain2 {
            get {
                return ResourceManager.GetString("Certain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken breast: 500 grams (cut into small cubes).
        /// </summary>
        public static string Chickenbreast6 {
            get {
                return ResourceManager.GetString("Chickenbreast6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chickenbroth: 4 cups.
        /// </summary>
        public static string Chickenbroth4 {
            get {
                return ResourceManager.GetString("Chickenbroth4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grilled chicken with lemon dressing and herbs for diet.
        /// </summary>
        public static string chickenherbs {
            get {
                return ResourceManager.GetString("chickenherbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chicken with hot pepper for diet.
        /// </summary>
        public static string Chickenhot {
            get {
                return ResourceManager.GetString("Chickenhot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese pumpkin dumplings with lower calories.
        /// </summary>
        public static string Chinesepumpkin {
            get {
                return ResourceManager.GetString("Chinesepumpkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinnamon: 1 tablespoon (soft).
        /// </summary>
        public static string Cinnamon7 {
            get {
                return ResourceManager.GetString("Cinnamon7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiments: Salt, pepper, vinegar, lemon juice, fresh herbs and spices..
        /// </summary>
        public static string Condiments2 {
            get {
                return ResourceManager.GetString("Condiments2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking Cream: (Light) Cup.
        /// </summary>
        public static string CookingCream1 {
            get {
                return ResourceManager.GetString("CookingCream1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A crisp pancake with cherry low-calorie.
        /// </summary>
        public static string crisppancake {
            get {
                return ResourceManager.GetString("crisppancake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumin: half a teaspoon (ground).
        /// </summary>
        public static string Cumin2 {
            get {
                return ResourceManager.GetString("Cumin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumin: 4 tablespoon (ground).
        /// </summary>
        public static string Cumin7 {
            get {
                return ResourceManager.GetString("Cumin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Weight.
        /// </summary>
        public static string CurrentWeight {
            get {
                return ResourceManager.GetString("CurrentWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Five.
        /// </summary>
        public static string DayFive {
            get {
                return ResourceManager.GetString("DayFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Four.
        /// </summary>
        public static string DayFour {
            get {
                return ResourceManager.GetString("DayFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day One.
        /// </summary>
        public static string DayOne {
            get {
                return ResourceManager.GetString("DayOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Seven.
        /// </summary>
        public static string DaySeven {
            get {
                return ResourceManager.GetString("DaySeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Six.
        /// </summary>
        public static string DaySix {
            get {
                return ResourceManager.GetString("DaySix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Three.
        /// </summary>
        public static string DayThree {
            get {
                return ResourceManager.GetString("DayThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Two.
        /// </summary>
        public static string DayTwo {
            get {
                return ResourceManager.GetString("DayTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dessert.
        /// </summary>
        public static string Dessert {
            get {
                return ResourceManager.GetString("Dessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Diet&quot; and &quot;low-fat&quot; foods: These are usually very high in sugar..
        /// </summary>
        public static string Dietandlowfat1 {
            get {
                return ResourceManager.GetString("Dietandlowfat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet program.
        /// </summary>
        public static string Dietprogram {
            get {
                return ResourceManager.GetString("Dietprogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet programs.
        /// </summary>
        public static string Dietprograms {
            get {
                return ResourceManager.GetString("Dietprograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dough for kibbeh.
        /// </summary>
        public static string Dough7 {
            get {
                return ResourceManager.GetString("Dough7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dough for kibbeh.
        /// </summary>
        public static string Dough71 {
            get {
                return ResourceManager.GetString("Dough71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dough is divided into two halves: the first half is well thinner, then extend in the bottom of the tray until it is covered, and the filling is added. Divide the second half of the dough into sections, separate the latter, and place on top of the boil next to each other, until the filling is completely covered. With wet fingers, the surface is smoothed, until smooth..
        /// </summary>
        public static string doughis7 {
            get {
                return ResourceManager.GetString("doughis7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry basil: half a teaspoon (ground).
        /// </summary>
        public static string Drybasil1 {
            get {
                return ResourceManager.GetString("Drybasil1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggs: The healthiest eggs are omega-3 enriched or pastured..
        /// </summary>
        public static string Eggs1 {
            get {
                return ResourceManager.GetString("Eggs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggs: Pastured, organic whole eggs make the best choice..
        /// </summary>
        public static string Eggs2 {
            get {
                return ResourceManager.GetString("Eggs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        public static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatty fish and seafood: Salmon, trout, sardines, etc..
        /// </summary>
        public static string Fattyfish1 {
            get {
                return ResourceManager.GetString("Fattyfish1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatty fish:Wild-caught salmon, herring and mackerel.
        /// </summary>
        public static string Fattyfish2 {
            get {
                return ResourceManager.GetString("Fattyfish2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling.
        /// </summary>
        public static string Filling {
            get {
                return ResourceManager.GetString("Filling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine white bulgur: a cup.
        /// </summary>
        public static string Finewhite5 {
            get {
                return ResourceManager.GetString("Finewhite5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grilled fish with lemon for diet.
        /// </summary>
        public static string fish {
            get {
                return ResourceManager.GetString("fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flour: 4 tablespoons.
        /// </summary>
        public static string Flour7 {
            get {
                return ResourceManager.GetString("Flour7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For stuffing: add onions, with spices, to the meat&apos;s electric machine..
        /// </summary>
        public static string Forstuffing7 {
            get {
                return ResourceManager.GetString("Forstuffing7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit: Citrus, grapes, bananas and pineapple.
        /// </summary>
        public static string Fruits2 {
            get {
                return ResourceManager.GetString("Fruits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Full-fat yogurt topped with Keto granola.
        /// </summary>
        public static string Fullfat {
            get {
                return ResourceManager.GetString("Fullfat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullfatcheese : Cheddar, mozzarella, brie, goat cheese and cream cheese..
        /// </summary>
        public static string Fullfatcheese2 {
            get {
                return ResourceManager.GetString("Fullfatcheese2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-fat dairy: Butter, cheese, cream, full-fat yogurt..
        /// </summary>
        public static string Fullfatdairy1 {
            get {
                return ResourceManager.GetString("Fullfatdairy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-fat dairy: Yogurt, butter and cream.
        /// </summary>
        public static string Fullfatdairy2 {
            get {
                return ResourceManager.GetString("Fullfatdairy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name Arabic.
        /// </summary>
        public static string FullNameArabic {
            get {
                return ResourceManager.GetString("FullNameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name English.
        /// </summary>
        public static string FullNameEnglish {
            get {
                return ResourceManager.GetString("FullNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garlic: 2 cloves (crushed).
        /// </summary>
        public static string Garlic1 {
            get {
                return ResourceManager.GetString("Garlic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garlic: 3 cloves (minced).
        /// </summary>
        public static string Garliccloves4 {
            get {
                return ResourceManager.GetString("Garliccloves4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grains: Wheat, spelt, rye, barley, rice..
        /// </summary>
        public static string Grains1 {
            get {
                return ResourceManager.GetString("Grains1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and grain products: Wheat, rice, oats, breakfast cereals and tortillas.
        /// </summary>
        public static string Grains2 {
            get {
                return ResourceManager.GetString("Grains2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green chard: 10 leaves (medium size / finely chopped).
        /// </summary>
        public static string Greenchard7 {
            get {
                return ResourceManager.GetString("Greenchard7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Coriander: 2 teaspoon (fresh and chopped).
        /// </summary>
        public static string GreenCoriander2 {
            get {
                return ResourceManager.GetString("GreenCoriander2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Coriander: 2 tbsp (minced).
        /// </summary>
        public static string GreenCoriander6 {
            get {
                return ResourceManager.GetString("GreenCoriander6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grilledchicken with lemon dressing and herbs for diet.
        /// </summary>
        public static string Grilledchicken {
            get {
                return ResourceManager.GetString("Grilledchicken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grilled salmon with spinach sauteed in coconut oil.
        /// </summary>
        public static string Grilledsalmon {
            get {
                return ResourceManager.GetString("Grilledsalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands and Feet Exercise.
        /// </summary>
        public static string HandsandFeetExercise {
            get {
                return ResourceManager.GetString("HandsandFeetExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands and Feet Exercises.
        /// </summary>
        public static string HandsandFeetExercises {
            get {
                return ResourceManager.GetString("HandsandFeetExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands and Waist Exercises.
        /// </summary>
        public static string HandsandWaistExercises {
            get {
                return ResourceManager.GetString("HandsandWaistExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Healthy living&quot; to most people means both physical and mental health are in balance or functioning well together in a person. In many instances, physical and mental health are closely linked, so that a change (good or bad) in one directly affects the other. Consequently, some of the tips will include suggestions for emotional and mental &quot;healthy living..
        /// </summary>
        public static string Healthy {
            get {
                return ResourceManager.GetString("Healthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy fats: Extra virgin olive oil, coconut oil, avocados and avocado oil..
        /// </summary>
        public static string Healthyfats1 {
            get {
                return ResourceManager.GetString("Healthyfats1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy fats: Coconut oil, olive oil, avocado oil, coconut butter and sesame oil..
        /// </summary>
        public static string Healthyfats2 {
            get {
                return ResourceManager.GetString("Healthyfats2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat a thick, wide skillet over medium heat, then add oil and meat and stir the meat for 3 minutes until it becomes brown..
        /// </summary>
        public static string Heatathick2 {
            get {
                return ResourceManager.GetString("Heatathick2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat the oil in a large skillet over medium heat, add onions and stir for 5 minutes until wilted..
        /// </summary>
        public static string Heatthe1 {
            get {
                return ResourceManager.GetString("Heatthe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat the oil in a large skillet over medium heat, season the chicken with salt and pepper, and stir the chicken with the oil for 5 minutes, until browned and done, then set aside..
        /// </summary>
        public static string Heatthe6 {
            get {
                return ResourceManager.GetString("Heatthe6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-carbsauces: Barbecue sauce, sugary salad dressings and dipping sauces.
        /// </summary>
        public static string Highcarb2 {
            get {
                return ResourceManager.GetString("Highcarb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-carb fruits: Bananas, apples, oranges, pears, grapes (induction only)..
        /// </summary>
        public static string Highcarbfruits1 {
            get {
                return ResourceManager.GetString("Highcarbfruits1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-carb vegetables : Carrots, turnips, etc (induction only)..
        /// </summary>
        public static string Highcarbvegetables {
            get {
                return ResourceManager.GetString("Highcarbvegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honey: half a cup.
        /// </summary>
        public static string Honeyhalf6 {
            get {
                return ResourceManager.GetString("Honeyhalf6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot pepper: 1 grain (chopped).
        /// </summary>
        public static string Hotpepper6 {
            get {
                return ResourceManager.GetString("Hotpepper6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to prepare.
        /// </summary>
        public static string Howto {
            get {
                return ResourceManager.GetString("Howto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal Weight.
        /// </summary>
        public static string IdealWeight {
            get {
                return ResourceManager.GetString("IdealWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a small bowl, mix the starch and 1 tablespoon of water and set aside..
        /// </summary>
        public static string Inasmall6 {
            get {
                return ResourceManager.GetString("Inasmall6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        public static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low-carb vegetables: Kale, spinach, broccoli, asparagus and others..
        /// </summary>
        public static string Kale1 {
            get {
                return ResourceManager.GetString("Kale1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This diet mainly aims to reduce carbohydrate consumption and increase the consumption of healthy fats such as avocado, coconut, brazilian nuts, fatty fish seeds and olive oil. This may sound illogical to some, but it allows the body to focus on burning fat and using it as an energy source. This diet causes the accumulated fat to be destroyed and converted into products called ketones. However, it carries a risk of developing hyperkitonemia in patients with type 1 diabetes, but studies are still ongoing..
        /// </summary>
        public static string Ketogenic {
            get {
                return ResourceManager.GetString("Ketogenic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ketogenic diet.
        /// </summary>
        public static string Ketogenicdiet {
            get {
                return ResourceManager.GetString("Ketogenicdiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Leftover chicken and veggies from the night before..
        /// </summary>
        public static string Leftoverchicken1 {
            get {
                return ResourceManager.GetString("Leftoverchicken1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legumes: Lentils, beans, chickpeas, etc..
        /// </summary>
        public static string Legumes1 {
            get {
                return ResourceManager.GetString("Legumes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemon juice: 1 tablespoon.
        /// </summary>
        public static string Lemonjuice3 {
            get {
                return ResourceManager.GetString("Lemonjuice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemon juice: a quarter cup.
        /// </summary>
        public static string Lemonjuice5 {
            get {
                return ResourceManager.GetString("Lemonjuice5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemon juice: 1 pill.
        /// </summary>
        public static string Lemonjuice6 {
            get {
                return ResourceManager.GetString("Lemonjuice6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowerBodyExercises.
        /// </summary>
        public static string LowerBodyExercises {
            get {
                return ResourceManager.GetString("LowerBodyExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marinated chicken steak.
        /// </summary>
        public static string Marinatedchicken {
            get {
                return ResourceManager.GetString("Marinatedchicken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat:Grass-fed beef, venison, organ meats and bison.
        /// </summary>
        public static string Meat2 {
            get {
                return ResourceManager.GetString("Meat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat Fillet: 500 grams (longitudinal sliced section).
        /// </summary>
        public static string MeatFillet1 {
            get {
                return ResourceManager.GetString("MeatFillet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meats: Beef,  lamb, chicken, and others..
        /// </summary>
        public static string Meats1 {
            get {
                return ResourceManager.GetString("Meats1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediterranean diet.
        /// </summary>
        public static string Medi {
            get {
                return ResourceManager.GetString("Medi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It means following the eating habits of southern Europeans such as Greece, Crete, southern Italy, Spain, southern France and Portugal as well. The focus is on eating vegetable foods, fresh fruits, nuts, beans, whole grains, seeds, olive oil, cheese, and milk. Moderate amounts of fish, chicken, and eggs can be eaten, and small amounts of red meat. This diet has been studied extensively and has proven effective in improving the quality of life and reducing the risk of disease.
        ///                Finally, it mus [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Mediterranean {
            get {
                return ResourceManager.GetString("Mediterranean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a medium heat pot, mix honey, garlic, lemon, soy sauce, apple cider vinegar, sesame oil and chopped pepper, and stir until boiling.
        /// </summary>
        public static string mediumheat6 {
            get {
                return ResourceManager.GetString("mediumheat6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly diet program.
        /// </summary>
        public static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaage.
        /// </summary>
        public static string Messaage {
            get {
                return ResourceManager.GetString("Messaage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix the scourer with the electric mixer until it becomes a smooth mixture, return it to a saucepan and heat it..
        /// </summary>
        public static string Mixthe4 {
            get {
                return ResourceManager.GetString("Mixthe4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix the water with the remaining amount of oil well, pour it on the surface of the tray of kibbeh, and distribute it over it. The tray is covered with aluminum foil, and cooked in a preheated oven, at a temperature of 200 degrees Celsius, for forty minutes. After the mentioned time has passed, the aluminum foil is removed from the tray. The oven is heated from above. Bake the tray for five minutes..
        /// </summary>
        public static string Mixthe7 {
            get {
                return ResourceManager.GetString("Mixthe7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix tomatoes, cucumbers, parsley in a dish, add bulgur and my heart..
        /// </summary>
        public static string Mixtomatoes5 {
            get {
                return ResourceManager.GetString("Mixtomatoes5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushroom chicken for a balanced diet.
        /// </summary>
        public static string Mushroomchicken {
            get {
                return ResourceManager.GetString("Mushroomchicken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mushroomomelet.
        /// </summary>
        public static string Mushroomomelet {
            get {
                return ResourceManager.GetString("Mushroomomelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string Myprofile {
            get {
                return ResourceManager.GetString("Myprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Arabic.
        /// </summary>
        public static string NameArabic {
            get {
                return ResourceManager.GetString("NameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name English.
        /// </summary>
        public static string NameEnglish {
            get {
                return ResourceManager.GetString("NameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nut butter: Natural peanut, almond and cashew butters..
        /// </summary>
        public static string Nutbutter2 {
            get {
                return ResourceManager.GetString("Nutbutter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutmeg: a quarter of a teaspoon.
        /// </summary>
        public static string Nutmeg4 {
            get {
                return ResourceManager.GetString("Nutmeg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuts and seeds: Almonds, macadamia nuts, walnuts, sunflower seeds, etc..
        /// </summary>
        public static string Nutsandseeds1 {
            get {
                return ResourceManager.GetString("Nutsandseeds1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuts and seeds: Macadamia nuts, almonds, walnuts, pumpkin seeds, peanuts and flaxseeds..
        /// </summary>
        public static string Nutsandseeds2 {
            get {
                return ResourceManager.GetString("Nutsandseeds2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat oil in a frying pan, add onions, and stir until it becomes light-colored. Then, add the chard with salt and sweet pepper, stirring constantly for five minutes, noting that the chard has wilted. Add walnuts and pomegranate molasses, mixing well. Place the filling mixture aside..
        /// </summary>
        public static string oilin7 {
            get {
                return ResourceManager.GetString("oilin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive oil: 1 tablespoon.
        /// </summary>
        public static string Oliveoil1 {
            get {
                return ResourceManager.GetString("Oliveoil1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat oliveoil in a saucepan over medium heat, then add onions and garlic and stir until soft..
        /// </summary>
        public static string oliveoil4 {
            get {
                return ResourceManager.GetString("oliveoil4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive oil: 1 tablespoon.
        /// </summary>
        public static string Oliveoil5 {
            get {
                return ResourceManager.GetString("Oliveoil5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onions: 1 grain (finely chopped).
        /// </summary>
        public static string Onions1 {
            get {
                return ResourceManager.GetString("Onions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onions: 1 grain (chopped slices).
        /// </summary>
        public static string Onions2 {
            get {
                return ResourceManager.GetString("Onions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onions: 2 tablets (medium size / peeled and cut into large pieces).
        /// </summary>
        public static string Onions7 {
            get {
                return ResourceManager.GetString("Onions7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onions: 1 grain (chopped).
        /// </summary>
        public static string Onionsgrain4 {
            get {
                return ResourceManager.GetString("Onionsgrain4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onions: 2 grains (medium size / finely chopped).
        /// </summary>
        public static string Onionsgrains7 {
            get {
                return ResourceManager.GetString("Onionsgrains7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option: 1 piece (finely chopped).
        /// </summary>
        public static string Option5 {
            get {
                return ResourceManager.GetString("Option5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsley: 2 teaspoon.
        /// </summary>
        public static string Parsley5 {
            get {
                return ResourceManager.GetString("Parsley5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasta: Bottle (preferred shape).
        /// </summary>
        public static string Pasta1 {
            get {
                return ResourceManager.GetString("Pasta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaghetti and noodles.
        /// </summary>
        public static string pasta2 {
            get {
                return ResourceManager.GetString("pasta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peas: a cup (frozen).
        /// </summary>
        public static string Peas3 {
            get {
                return ResourceManager.GetString("Peas3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PilatesExercise.
        /// </summary>
        public static string PilatesExercise {
            get {
                return ResourceManager.GetString("PilatesExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomegranate molasses: 4 tablespoons.
        /// </summary>
        public static string Pomegranate7 {
            get {
                return ResourceManager.GetString("Pomegranate7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pork chops with green beans sauteed in coconut oil.
        /// </summary>
        public static string Porkchops2 {
            get {
                return ResourceManager.GetString("Porkchops2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potato and eggplant soup for diet.
        /// </summary>
        public static string Potato {
            get {
                return ResourceManager.GetString("Potato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potatoes: 1 grain (small and chopped).
        /// </summary>
        public static string Potatoesgrain4 {
            get {
                return ResourceManager.GetString("Potatoesgrain4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poultry:Chicken and turkey.
        /// </summary>
        public static string Poultry2 {
            get {
                return ResourceManager.GetString("Poultry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour the pasta into dishes and serve hot..
        /// </summary>
        public static string Pourthe1 {
            get {
                return ResourceManager.GetString("Pourthe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed foods: Fast food, packaged foods and processed meats such as hot dogs and lunch meats.
        /// </summary>
        public static string Processedfoods2 {
            get {
                return ResourceManager.GetString("Processedfoods2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumpkin: 5 kg (fresh).
        /// </summary>
        public static string Pumpkin7 {
            get {
                return ResourceManager.GetString("Pumpkin7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pumpkin is peeled off with a knife, then cut into large cubes, noting that after processing it, the pumpkin will produce about 3 and a half kilograms. Boil the pumpkin cubes for twenty minutes, noting the full ripeness. Then, drain the cubes well, and set aside..
        /// </summary>
        public static string Pumpkinis7 {
            get {
                return ResourceManager.GetString("Pumpkinis7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This diet means that at least 75% of your food should be uncooked, untreated, or raw. And vegans make up a large proportion of followers of this diet..
        /// </summary>
        public static string Rawfood {
            get {
                return ResourceManager.GetString("Rawfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw food diet.
        /// </summary>
        public static string Rawfooddiet {
            get {
                return ResourceManager.GetString("Rawfooddiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes Book.
        /// </summary>
        public static string RecipesBook {
            get {
                return ResourceManager.GetString("RecipesBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red hot pepper: half a teaspoon (ground).
        /// </summary>
        public static string Redhotpepper2 {
            get {
                return ResourceManager.GetString("Redhotpepper2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red pepper: 1 tablet (chopped slices).
        /// </summary>
        public static string redpepper2 {
            get {
                return ResourceManager.GetString("redpepper2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce the heat, then add the starch mixture, stirring, and stir for two minutes until the mixture thickens..
        /// </summary>
        public static string Reducethe6 {
            get {
                return ResourceManager.GetString("Reducethe6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roast chicken with cream sauce and sauteed broccoli.
        /// </summary>
        public static string Roastchicken2 {
            get {
                return ResourceManager.GetString("Roastchicken2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt: 2 tablespoon.
        /// </summary>
        public static string Salt7 {
            get {
                return ResourceManager.GetString("Salt7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt: half a teaspoon.
        /// </summary>
        public static string Salthalf1 {
            get {
                return ResourceManager.GetString("Salthalf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indian samosa.
        /// </summary>
        public static string samosa {
            get {
                return ResourceManager.GetString("samosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season the meat with salt and pepper, and stir for another minute, then lift the meat from the pan and set it aside..
        /// </summary>
        public static string Seasonthe2 {
            get {
                return ResourceManager.GetString("Seasonthe2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season with salt, pepper and nutmeg and serve hot..
        /// </summary>
        public static string Seasonwith4 {
            get {
                return ResourceManager.GetString("Seasonwith4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasonwith salt, pepper and olive oil, and serve..
        /// </summary>
        public static string Seasonwith5 {
            get {
                return ResourceManager.GetString("Seasonwith5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Now.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serve warm or cold to taste, along with grilled meat or chicken..
        /// </summary>
        public static string Servewarm3 {
            get {
                return ResourceManager.GetString("Servewarm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesame: half a teaspoon.
        /// </summary>
        public static string Sesame6 {
            get {
                return ResourceManager.GetString("Sesame6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesame oil: a teaspoon.
        /// </summary>
        public static string Sesameoil6 {
            get {
                return ResourceManager.GetString("Sesameoil6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple diet program.
        /// </summary>
        public static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simple diet.
        /// </summary>
        public static string simplediet {
            get {
                return ResourceManager.GetString("simplediet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snack.
        /// </summary>
        public static string Snack {
            get {
                return ResourceManager.GetString("Snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soak the bulgur with lemon juice and leave it for half an hour until the mixture is absorbed and then stir with a fork..
        /// </summary>
        public static string Soakthe5 {
            get {
                return ResourceManager.GetString("Soakthe5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This diet was started by Agatston, a cardiologist and Marie Almon. This diet focuses on controlling insulin levels and taking advantage of slow, unrefined carbohydrates. Dr. Agatston created this diet after which he was frustrated with the low-fat, high-carb diet that was supported by the American Heart Association..
        /// </summary>
        public static string SouthBeach {
            get {
                return ResourceManager.GetString("SouthBeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Beach diet.
        /// </summary>
        public static string SouthBeachdiet {
            get {
                return ResourceManager.GetString("SouthBeachdiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soy sauce: 1 tablespoon.
        /// </summary>
        public static string Soysauce6 {
            get {
                return ResourceManager.GetString("Soysauce6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squeeze the pumpkin, and add it with flour, to the onion and bulgur mixture in the machine. Ingredients beat until obtaining a cohesive dough. Put the dough aside. An indication that more flour can be added if needed..
        /// </summary>
        public static string Squeeze7 {
            get {
                return ResourceManager.GetString("Squeeze7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starch: 1 tablespoon.
        /// </summary>
        public static string Starch6 {
            get {
                return ResourceManager.GetString("Starch6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starches: Potatoes, sweet potatoes (induction only)..
        /// </summary>
        public static string Starches1 {
            get {
                return ResourceManager.GetString("Starches1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starchy vegetables: Potatoes, sweet potatoes, butternut squash, corn, peas and pumpkin.
        /// </summary>
        public static string Starchy2 {
            get {
                return ResourceManager.GetString("Starchy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Steak bowl with cauliflower rice, cheese, herbs, avocado and salsa..
        /// </summary>
        public static string Steakbowl {
            get {
                return ResourceManager.GetString("Steakbowl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Details.
        /// </summary>
        public static string StepDetails {
            get {
                return ResourceManager.GetString("StepDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stomach and Abdominal Exercises.
        /// </summary>
        public static string StomachandAbdominalExercises {
            get {
                return ResourceManager.GetString("StomachandAbdominalExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugar: Soft drinks, fruit juices, cakes, candy, ice cream, etc..
        /// </summary>
        public static string Sugar1 {
            get {
                return ResourceManager.GetString("Sugar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweet pepper: a teaspoon.
        /// </summary>
        public static string Sweet7 {
            get {
                return ResourceManager.GetString("Sweet7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soda, juice, sweetened teas and sports drinks..
        /// </summary>
        public static string SweetenedBeverages2 {
            get {
                return ResourceManager.GetString("SweetenedBeverages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweet pepper: 4 tablespoon.
        /// </summary>
        public static string Sweetpepper7 {
            get {
                return ResourceManager.GetString("Sweetpepper7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targe tWeight.
        /// </summary>
        public static string TargetWeight {
            get {
                return ResourceManager.GetString("TargetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The Calorie Calculator can be used to estimate the number of calories a person needs to consume each day. This calculator can also provide some simple guidelines for gaining or losing weigh.
        /// </summary>
        public static string TheCalorieCalculator {
            get {
                return ResourceManager.GetString("TheCalorieCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tray content, with a sharp knife, is divided into small lozenges..
        /// </summary>
        public static string Thetray7 {
            get {
                return ResourceManager.GetString("Thetray7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foods to Avoid.
        /// </summary>
        public static string toAvoid {
            get {
                return ResourceManager.GetString("toAvoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foods toEat.
        /// </summary>
        public static string toEat {
            get {
                return ResourceManager.GetString("toEat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato: 1 grain (chopped slices).
        /// </summary>
        public static string Tomato5 {
            get {
                return ResourceManager.GetString("Tomato5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Body Exercise.
        /// </summary>
        public static string TotalBodyExercise {
            get {
                return ResourceManager.GetString("TotalBodyExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans fats: Usually found in processed foods with the word &quot;hydrogenated&quot; on the ingredients list..
        /// </summary>
        public static string Transfats1 {
            get {
                return ResourceManager.GetString("Transfats1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tray is divided into 8 equal portions. Serve hot..
        /// </summary>
        public static string trayis7 {
            get {
                return ResourceManager.GetString("trayis7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuna salad with celery and tomato atop a bed of greens.
        /// </summary>
        public static string Tuna2 {
            get {
                return ResourceManager.GetString("Tuna2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two eggs fried in pastured butter served with sauteed greens.
        /// </summary>
        public static string Twoeggs2 {
            get {
                return ResourceManager.GetString("Twoeggs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This diet is considered a philosophy more than a diet, so followers of this diet do not eat any food from animal origin such as milk, eggs or honey, and they never eat meat. This diet has ethical and environmental goals and principles in addition to nutritional goals. They think that eating only vegetarian food will benefit people, health and the environment and cause less suffering to animals..
        /// </summary>
        public static string Vegan {
            get {
                return ResourceManager.GetString("Vegan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan diet.
        /// </summary>
        public static string Vegandiet {
            get {
                return ResourceManager.GetString("Vegandiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetable broth: a quarter cup.
        /// </summary>
        public static string Vegetablebroth1 {
            get {
                return ResourceManager.GetString("Vegetablebroth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetable oil: 1 tablespoon.
        /// </summary>
        public static string Vegetableoil2 {
            get {
                return ResourceManager.GetString("Vegetableoil2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetable oils: Soybean oil, corn oil, cottonseed oil, canola oil and a few others..
        /// </summary>
        public static string Vegetableoils {
            get {
                return ResourceManager.GetString("Vegetableoils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-starchy vegetables: Greens, broccoli, tomatoes, mushrooms and peppers..
        /// </summary>
        public static string vegetables2 {
            get {
                return ResourceManager.GetString("vegetables2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are several types of plant-based diets such as the milk-based or egg-based diet or the half-vegetarian diet, but the most common is the vegetable diet with eggs and milk, that is, the person who is committed to it does not eat meat or animal products except for milk, eggs and honey. Studies show that vegetarians were less weight, healthier, and longer-lived compared to carnivores..
        /// </summary>
        public static string Vegetarian {
            get {
                return ResourceManager.GetString("Vegetarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarian diet.
        /// </summary>
        public static string Vegetariandiet {
            get {
                return ResourceManager.GetString("Vegetariandiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walnut: a cup (roughly chopped).
        /// </summary>
        public static string Walnut7 {
            get {
                return ResourceManager.GetString("Walnut7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Watchers diet.
        /// </summary>
        public static string Watchers {
            get {
                return ResourceManager.GetString("Watchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water: 2 tablespoons.
        /// </summary>
        public static string Water7 {
            get {
                return ResourceManager.GetString("Water7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight.
        /// </summary>
        public static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This diet focuses on losing weight through a specific diet, exercise and social support network. Weight Watchers is a global company with branches around the world, started in the sixties of the last century by a woman who lost some weight and feared to gain it again, so she formed a network of friends that later evolved into this company. You can join this network, either personally, by attending regular meetings or via the Internet for support and nutritional education..
        /// </summary>
        public static string WeightWatchers {
            get {
                return ResourceManager.GetString("WeightWatchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe a Chinese bottom (30 x 40 centimeters) with a tablespoon of oil..
        /// </summary>
        public static string Wipe7 {
            get {
                return ResourceManager.GetString("Wipe7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow pepper: 1 tablet (sliced minced).
        /// </summary>
        public static string Yellowpepper2 {
            get {
                return ResourceManager.GetString("Yellowpepper2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This diet aims to achieve a nutritional balance by consuming 40% carbohydrates, 30% fats and 30% protein in each meal. The main goal is to control insulin levels, which will achieve better results in weight loss or control. This diet encourages consumption of high-quality and unrefined carbohydrates in addition to some fats such as olive oil, avocado and nuts..
        /// </summary>
        public static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone diet.
        /// </summary>
        public static string Zonediet {
            get {
                return ResourceManager.GetString("Zonediet", resourceCulture);
            }
        }
    }
}
